#! /usr/bin/python
# -*- coding=utf-8 -*-
#bt-tools - tools to interact with some bittorrent sites by commandline
#Copyright (C) 2015-2016  varogami@altervista.org

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

from lib import config
from lib import utils
from lib import common
import sys

class Func:
    def __init__(self):
        self.__conf = config.Config()
        self.__color = self.__conf.getColors()
        self.__json = self.__conf.getJson()
        self.__db = self.__conf.getDb()
        self.__debug = self.__conf.getDebug()
        self.common = common.Func(self.__conf)
    
    def iterative_download(self, args):
        for id in args:
            if not id == args[0]:
                self.common.download(id, args[1])

    def cli(self):
        if len(sys.argv) == 1:
            self.help()
        else:
            self.iterative_download(sys.argv)

    def help(self):
        print "use:"
        print "bt-download MODE ID01 ID02 ID03 ...."
        print "     MODE               - is how download torrent"
        print "     ID01 ID02 ... IDXX - are id of bt-search result"
        print "or"
        print
        print "bt-download ID01 ID02 ID03 ...."

                        
if __name__ == "__main__":
    do = Func()
    do.cli()
