#! /usr/bin/python
# -*- coding=utf-8 -*-
#bt-tools - tools to interact with some bittorrent sites by commandline
#Copyright (C) 2015  varogami

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

from modules import utils
from lib import config
from lib import xml
from lib import common
import sys

class Func:
    def __init__(self):
        self.engines = config.engines

    def iterative_download(self, args):
        #find element's engine
        isValidType = False
        for engine in self.engines.values():
            if args[1] == engine.shortname:
                isValidType = True
                for id in args:
                    if not id == args[0]:
                        if not id == args[1]:
                            common.Func().download(args[1] + "-" + id)
                            print
        if not isValidType:
            print "not valid " + args[1] + "-" + id



class CLI:
    def __init__(self):
        if len(sys.argv) == 1:
            self.help()
        elif len(sys.argv) == 2:
            common.Func().print_error("bad parameters")
        else:
            Func().iterative_download(sys.argv)

    def help(self):
        print "use:"
        print "bt-download SITECODE ID01 ID02 ID03 ...."
        print "     ID01 ID02 ... are id of bt-search result"

                        
if __name__ == "__main__":
    do = CLI()
