#! /usr/bin/python
# -*- coding=utf-8 -*-
#bt-tools - tools to interact with some bittorrent sites by commandline
#Copyright (C) 2015  varogami

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

from modules import utils
from lib import config
from lib import utils
from lib import common
import sys

class Func:
    def __init__(self):
        self.__conf = config.Config()
        self.__color = self.__conf.getColors()
        self.__json = self.__conf.getJson()
        self.__db = self.__conf.getDb()
        self.__debug = self.__conf.getDebug()
        self.__common = common.Func(self.__color, self.getModules())

    def getColors(self):
        return self.__color

    def getModules(self):
        return self.__json['module']
    
    def iterative_download(self, args):
        for id in args:
            if not id == args[0]:
                self.common.download(id)

class CLI:
    def __init__(self):
        self.do = Func()
        self.color = self.do.getColors()
        self.common = common.Func(self.color, self.do.getModules())
        
        if len(sys.argv) == 1:
            self.help()
        elif len(sys.argv) == 2:
            self.common.print_error("bad parameters")
        else:
            self.do.iterative_download(sys.argv)

    def help(self):
        print "use:"
        print "bt-download SITECODE ID01 ID02 ID03 ...."
        print "     ID01 ID02 ... are id of bt-search result"

                        
if __name__ == "__main__":
    do = CLI()
