#!/bin/bash
#bt-tools - tools to interact with some bittorrent sites by commandline
#Copyright (C) 2015  varogami

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

TIME=2400
MIN="$(bc <<< "scale=2; ($TIME/60)")"
CMD='bt-rss-fix'
#CMD='bt-rss-daemon-core' #used with bt-conky

while [ 1 ]
do
    if ping -c1 www.google.com &> /dev/null
    then 
	$CMD
    fi
    echo "wait $TIME sec ($MIN min)"
    sleep $TIME
    clear
done



