#!/bin/bash 

help_color="#0C73C2"
#help_color="#5F5F5F"
BT_SEARCH="$(dirname $0)/bt-search"
BT_DOWN="$(dirname $0)/bt-download"

set_msg(){
    MSG="<span size='small' color='$help_color'>$1</span>"
}

check_bt_config(){
    echo true
}

set_msg "insert words to search"
WORDS=$(echo "" | rofi -dmenu -hide-scrollbar -lines 1 -mesg "$MSG" -p "bt-search:")

if [ -z "$WORDS" ]
then
    echo nowords
else
    set_msg "SHIFT+RETURN to multiselect"
    TO_DOWNLOAD=""
    $BT_SEARCH "$WORDS" cache | rofi -dmenu -lines 30 -multi-select -p "bt-download:" -mesg "$MSG" -font "mono 9" -width 80 -i > ~/.cache/bt-rofi
    while read LINE
    do
	ITEM="$(echo "$LINE" | awk '{print $1}')"
	TO_DOWNLOAD="$TO_DOWNLOAD $ITEM"
    done < ~/.cache/bt-rofi
    rm ~/.cache/bt-rofi

    if [ ! -z $TO_DOWNLOAD ]
    then
	$BT_DOWN $TO_DOWNLOAD | rofi -dmenu -width 80 -p "to download:" -font "mono 9"
    fi
fi
